### ISSUE TITLE
Delete?!

### ISSUE THREAD

**Issue by 4ware** [benawad/silent-auction-rn#1]
Hi!

I know, old project :) But how would you implement a delete action for, say an auction?

Thanks, Kai

**Comment by benawad** [comment]
You'd want to call the delete endpoint. I will make a video that will come out on Sunday that goes into detail on how this works.

**Comment by 4ware** [comment]
Fantastic! I'm looking forward to it! And while you're at it why not tackle editing too :) ?

**Comment by benawad** [comment]
For sure!

**Comment by benawad** [comment]
https://youtu.be/MAWNtg6HCJQ
